"""Initial migration

Revision ID: 14e41da7f7a4
Revises:
Create Date: 2021-08-07 21:19:29.546557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14e41da7f7a4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label",
        sa.Column(
            "id", sa.Integer().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "meeting",
        sa.Column(
            "id", sa.Integer().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("date_started", sa.DateTime(), nullable=False),
        sa.Column("date_ended", sa.DateTime(), nullable=True),
        sa.Column("link", sa.String(length=500), server_default="", nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "participant",
        sa.Column(
            "id", sa.Integer().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "meetings_labels",
        sa.Column(
            "meeting_id",
            sa.Integer().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "label_id",
            sa.Integer().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["label.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.id"],
        ),
        sa.PrimaryKeyConstraint("meeting_id", "label_id"),
    )
    op.create_table(
        "meetings_participants",
        sa.Column(
            "meeting_id",
            sa.Integer().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "participant_id",
            sa.Integer().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meeting.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participant.id"],
        ),
        sa.PrimaryKeyConstraint("meeting_id", "participant_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meetings_participants")
    op.drop_table("meetings_labels")
    op.drop_table("participant")
    op.drop_table("meeting")
    op.drop_table("label")
    # ### end Alembic commands ###
